# Copyright (c) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

custdata_sample_src = [
  "main.c",
  "src/custdata_sample_common.c",
  "src/custdata_sample_publish.c",
  "src/custdata_sample_refresh.c",
  "src/custdata_sample_trans.c",
]

custdata_sample_inc = [
  "include",
  "//foundation/communication/dsoftbus/interfaces/kits/bus_center",
  "//foundation/communication/dsoftbus/interfaces/kits/common",
  "//foundation/communication/dsoftbus/interfaces/kits/transport",
  "//third_party/bounds_checking_function/include",
]

custdata_sample_deps = [
  "//foundation/communication/dsoftbus/sdk:softbus_client",
  "//third_party/bounds_checking_function:libsec_static",
]

if (defined(ohos_lite) && ohos_kernel_type == "liteos_m") {
  not_needed([
    "custdata_sample_src",
    "custdata_sample_inc",
    "custdata_sample_deps",
  ])
}

if (defined(ohos_lite)) {
  if (ohos_kernel_type == "liteos_m") {
    group("disc_coap_custdata_sample") {
    }
  } else {
    import("//build/lite/config/component/lite_component.gni")
    import("../../dsoftbus.gni")
    executable("disc_coap_custdata_sample") {
      sources = custdata_sample_src
      include_dirs = custdata_sample_inc
      deps = custdata_sample_deps
      libs = [ "pthread" ]
    }
  }
} else {
  import("//build/ohos.gni")
  ohos_executable("disc_coap_custdata_sample") {
    sources = custdata_sample_src
    include_dirs = custdata_sample_inc
    deps = custdata_sample_deps
    part_name = "dsoftbus"
    subsystem_name = "communication"
  }
}
