/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// [Start StaDynBuiltinArrayStDynIndex]
// dynamic_module/Index.ets
export { ArrayStChild } from './src/main/ets/components/ArrayStPage';
// [End StaDynBuiltinArrayStDynIndex]

// [Start StaDynBuiltinMapStDynIndex]
// dynamic_module/Index.ets
export { MapStChild } from './src/main/ets/components/MapStPage';
// [End StaDynBuiltinMapStDynIndex]

// [Start StaDynBuiltinSetStDynIndex]
// dynamic_module/Index.ets
export { SetStChild } from './src/main/ets/components/SetStPage';
// [End StaDynBuiltinSetStDynIndex]

// [Start StaDynBuiltinArrayEsDynIndex]
// dynamic_module/Index.ets
export { ArrayEsChild, dynCreateArray } from './src/main/ets/components/EsPage';
// [End StaDynBuiltinArrayEsDynIndex]

// [Start StaDynBuiltinMapEsDynIndex]
// dynamic_module/Index.ets
export { MapEsChild, dynCreateMap } from './src/main/ets/components/EsPage';
// [End StaDynBuiltinMapEsDynIndex]

// [Start StaDynBuiltinSetEsDynIndex]
// dynamic_module/Index.ets
export { SetEsChild, dynCreateSet } from './src/main/ets/components/EsPage';
// [End StaDynBuiltinSetEsDynIndex]
