export default class FriendMomentJsonUrl {
  public static readonly FRIEND_MOMENT_JSON_URL: Array<string> = [
    'https://gitee.com/openharmony/applications_app_samples/raw/master/code/Solutions/IM/Chat/features/chatlist/src/main/resources/rawfile/mockFriendMomentOneModelData.json',
    'https://gitee.com/openharmony/applications_app_samples/raw/master/code/Solutions/IM/Chat/features/chatlist/src/main/resources/rawfile/mockFriendMomentTwoModelData.json',
    'https://gitee.com/openharmony/applications_app_samples/raw/master/code/Solutions/IM/Chat/features/chatlist/src/main/resources/rawfile/mockFriendMomentThreeModelData.json'
  ]
  public static  CONNECT_TIME: number = 60000; // getWebData 中使用的连接时间
  public static  READ_TIME: number = 60000; // getWebData 中使用的读取时间
}