/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {

  static readonly HOME_TITLE: string = '随手记';
  static readonly IMG_WALL_TITLE: string = '图片墙';
  static readonly HELLO: string = '你好，';
  static readonly WELCOME_USE_JOT: string = '欢迎使用随手记。';
  static readonly ENTER_IN: string = '进入随手记';
  static readonly NOTES_TITLE: string = '笔记页';
  static readonly PLEASE_INPUT_NOTE_TITLE: string = '请输入笔记标题';
  static readonly NOTES_TIME: string = '16:60:22 上午';
  static readonly PLEASE_INPUT_NOTE_CONTENT: string = '请输入笔记内容';
  static readonly MIGRATION_SETTINGS: string = '迁移设置';
  static readonly MIGRATION_ABILITY: string = '迁移能力';
  static readonly MIGRATION_PAGE_STACK: string = '迁移页面栈';
  static readonly MIGRATION_SOURCE_END: string = '迁移后源端退出';
  static readonly TO_DO_LIST: string = '待办事项';
  static readonly LIST_ARRAY: Array<string> = ['8:00去健身房', '9:00工作', '12:30做午餐', '16：00见华小艺', '7:30做瑜伽', '14:30打网球', '11:30做午餐', '14：00打篮球', '20:30做瑜伽', '10:30洗衣服', '17:30做晚餐', '21：00见华小艺'];

}